/**
 * Base de dados de alimentos brasileiros
 * Macros por 100g (referencia: tabela TACO/UNICAMP + dados nutricionais comuns)
 *
 * Cada entrada:
 *   id: identificador unico
 *   nome: nome em portugues brasileiro
 *   categoria: proteina | carboidrato | gordura | fruta | vegetal | doce | bebida | composto
 *   kcal_per_100g, protein_per_100g, carb_per_100g, fat_per_100g
 *   unidade_referencia: { gramas, descricao } - sugestao de porcao padrao
 */
const TACO_FOODS = [
  // ===== PROTEINAS =====
  { id: "frango_peito_cru", nome: "Peito de frango cru", categoria: "proteina",
    kcal_per_100g: 110, protein_per_100g: 23, carb_per_100g: 0, fat_per_100g: 2,
    unidade_referencia: { gramas: 150, descricao: "1 file medio cru" } },
  { id: "frango_peito_cozido", nome: "Peito de frango cozido/grelhado", categoria: "proteina",
    kcal_per_100g: 165, protein_per_100g: 31, carb_per_100g: 0, fat_per_100g: 4,
    unidade_referencia: { gramas: 100, descricao: "1 file medio cozido" } },
  { id: "frango_sobrecoxa_cozida", nome: "Sobrecoxa de frango cozida (sem pele)", categoria: "proteina",
    kcal_per_100g: 175, protein_per_100g: 27, carb_per_100g: 0, fat_per_100g: 8,
    unidade_referencia: { gramas: 100, descricao: "1 sobrecoxa media" } },
  { id: "frango_desfiado", nome: "Frango desfiado cozido", categoria: "proteina",
    kcal_per_100g: 165, protein_per_100g: 30, carb_per_100g: 1, fat_per_100g: 4,
    unidade_referencia: { gramas: 60, descricao: "Recheio de 1 tapioca" } },
  { id: "patinho_moido_cru", nome: "Patinho moido cru (95% magro)", categoria: "proteina",
    kcal_per_100g: 150, protein_per_100g: 21, carb_per_100g: 0, fat_per_100g: 7,
    unidade_referencia: { gramas: 150, descricao: "1 porcao crua" } },
  { id: "coxao_mole_cozido", nome: "Coxao mole bovino cozido", categoria: "proteina",
    kcal_per_100g: 190, protein_per_100g: 31, carb_per_100g: 0, fat_per_100g: 7,
    unidade_referencia: { gramas: 100, descricao: "1 bife pequeno" } },
  { id: "tilapia_crua", nome: "Tilapia crua", categoria: "proteina",
    kcal_per_100g: 95, protein_per_100g: 20, carb_per_100g: 0, fat_per_100g: 2,
    unidade_referencia: { gramas: 150, descricao: "1 file medio" } },
  { id: "salmao_cru", nome: "Salmao cru", categoria: "proteina",
    kcal_per_100g: 210, protein_per_100g: 21, carb_per_100g: 0, fat_per_100g: 14,
    unidade_referencia: { gramas: 120, descricao: "1 posta" } },
  { id: "atum_agua_lata", nome: "Atum em agua (lata escorrida)", categoria: "proteina",
    kcal_per_100g: 110, protein_per_100g: 23, carb_per_100g: 0, fat_per_100g: 1,
    unidade_referencia: { gramas: 120, descricao: "1 lata escorrida" } },
  { id: "sardinha_oleo_lata", nome: "Sardinha em oleo (lata escorrida)", categoria: "proteina",
    kcal_per_100g: 210, protein_per_100g: 24, carb_per_100g: 0, fat_per_100g: 12,
    unidade_referencia: { gramas: 85, descricao: "1 lata escorrida" } },
  { id: "sardinha_tomate_lata", nome: "Sardinha em molho de tomate (lata)", categoria: "proteina",
    kcal_per_100g: 195, protein_per_100g: 23, carb_per_100g: 1, fat_per_100g: 11,
    unidade_referencia: { gramas: 85, descricao: "1 lata" } },
  { id: "ovo_inteiro", nome: "Ovo inteiro (cru/cozido)", categoria: "proteina",
    kcal_per_100g: 155, protein_per_100g: 13, carb_per_100g: 1, fat_per_100g: 11,
    unidade_referencia: { gramas: 50, descricao: "1 ovo medio" } },
  { id: "ovo_clara", nome: "Clara de ovo", categoria: "proteina",
    kcal_per_100g: 52, protein_per_100g: 11, carb_per_100g: 1, fat_per_100g: 0,
    unidade_referencia: { gramas: 33, descricao: "1 clara" } },
  { id: "ovo_gema", nome: "Gema de ovo", categoria: "proteina",
    kcal_per_100g: 320, protein_per_100g: 16, carb_per_100g: 1, fat_per_100g: 28,
    unidade_referencia: { gramas: 17, descricao: "1 gema" } },
  { id: "cottage", nome: "Queijo cottage", categoria: "proteina",
    kcal_per_100g: 100, protein_per_100g: 12, carb_per_100g: 4, fat_per_100g: 4,
    unidade_referencia: { gramas: 50, descricao: "2 col sopa" } },
  { id: "ricota_fresca", nome: "Ricota fresca", categoria: "proteina",
    kcal_per_100g: 175, protein_per_100g: 11, carb_per_100g: 3, fat_per_100g: 13,
    unidade_referencia: { gramas: 50, descricao: "1 fatia" } },
  { id: "queijo_branco_light", nome: "Queijo branco light", categoria: "proteina",
    kcal_per_100g: 200, protein_per_100g: 16, carb_per_100g: 4, fat_per_100g: 13,
    unidade_referencia: { gramas: 30, descricao: "1 fatia" } },
  { id: "mussarela", nome: "Mussarela", categoria: "proteina",
    kcal_per_100g: 280, protein_per_100g: 22, carb_per_100g: 2, fat_per_100g: 21,
    unidade_referencia: { gramas: 25, descricao: "1 fatia" } },
  { id: "peito_peru", nome: "Peito de peru fatiado (defumado)", categoria: "proteina",
    kcal_per_100g: 115, protein_per_100g: 18, carb_per_100g: 2, fat_per_100g: 4,
    unidade_referencia: { gramas: 30, descricao: "2 fatias" } },
  { id: "whey_concentrado", nome: "Whey concentrado (scoop 30g)", categoria: "proteina",
    kcal_per_100g: 370, protein_per_100g: 73, carb_per_100g: 7, fat_per_100g: 5,
    unidade_referencia: { gramas: 30, descricao: "1 scoop" } },
  { id: "leite_integral", nome: "Leite integral", categoria: "proteina", unit: "ml",
    kcal_per_100g: 60, protein_per_100g: 3.5, carb_per_100g: 5, fat_per_100g: 3.5,
    unidade_referencia: { gramas: 200, descricao: "1 copo (200ml)" } },
  { id: "leite_desnatado", nome: "Leite desnatado", categoria: "proteina", unit: "ml",
    kcal_per_100g: 35, protein_per_100g: 3.5, carb_per_100g: 5, fat_per_100g: 0,
    unidade_referencia: { gramas: 200, descricao: "1 copo (200ml)" } },
  { id: "iogurte_natural_integral", nome: "Iogurte natural integral", categoria: "proteina",
    kcal_per_100g: 65, protein_per_100g: 4, carb_per_100g: 5, fat_per_100g: 3,
    unidade_referencia: { gramas: 170, descricao: "1 pote" } },
  { id: "iogurte_natural_desnatado", nome: "Iogurte natural desnatado", categoria: "proteina",
    kcal_per_100g: 41, protein_per_100g: 4.5, carb_per_100g: 5, fat_per_100g: 0,
    unidade_referencia: { gramas: 170, descricao: "1 pote" } },

  // ===== CARBOIDRATOS =====
  { id: "arroz_branco_cozido", nome: "Arroz branco cozido", categoria: "carboidrato",
    kcal_per_100g: 130, protein_per_100g: 2.5, carb_per_100g: 28, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "4 col sopa" } },
  { id: "arroz_integral_cozido", nome: "Arroz integral cozido", categoria: "carboidrato",
    kcal_per_100g: 120, protein_per_100g: 3, carb_per_100g: 25, fat_per_100g: 1,
    unidade_referencia: { gramas: 100, descricao: "4 col sopa" } },
  { id: "macarrao_cozido", nome: "Macarrao cozido (semola)", categoria: "carboidrato",
    kcal_per_100g: 130, protein_per_100g: 5, carb_per_100g: 26, fat_per_100g: 1,
    unidade_referencia: { gramas: 150, descricao: "1 prato" } },
  { id: "batata_doce_cozida", nome: "Batata doce cozida", categoria: "carboidrato",
    kcal_per_100g: 90, protein_per_100g: 1.5, carb_per_100g: 21, fat_per_100g: 0,
    unidade_referencia: { gramas: 200, descricao: "1 unidade media" } },
  { id: "batata_inglesa_cozida", nome: "Batata inglesa cozida", categoria: "carboidrato",
    kcal_per_100g: 85, protein_per_100g: 2, carb_per_100g: 19, fat_per_100g: 0,
    unidade_referencia: { gramas: 150, descricao: "1 unidade media" } },
  { id: "mandioca_cozida", nome: "Mandioca cozida", categoria: "carboidrato",
    kcal_per_100g: 125, protein_per_100g: 1, carb_per_100g: 30, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 pedaco medio" } },
  { id: "inhame_cozido", nome: "Inhame cozido", categoria: "carboidrato",
    kcal_per_100g: 115, protein_per_100g: 1.5, carb_per_100g: 28, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 pedaco" } },
  { id: "feijao_preto_cozido", nome: "Feijao preto cozido", categoria: "carboidrato",
    kcal_per_100g: 120, protein_per_100g: 8, carb_per_100g: 22, fat_per_100g: 0.5,
    unidade_referencia: { gramas: 100, descricao: "1 concha" } },
  { id: "feijao_carioca_cozido", nome: "Feijao carioca cozido", categoria: "carboidrato",
    kcal_per_100g: 120, protein_per_100g: 8, carb_per_100g: 22, fat_per_100g: 0.5,
    unidade_referencia: { gramas: 100, descricao: "1 concha" } },
  { id: "lentilha_cozida", nome: "Lentilha cozida", categoria: "carboidrato",
    kcal_per_100g: 115, protein_per_100g: 9, carb_per_100g: 20, fat_per_100g: 0.5,
    unidade_referencia: { gramas: 100, descricao: "1 concha" } },
  { id: "grao_de_bico_cozido", nome: "Grao-de-bico cozido", categoria: "carboidrato",
    kcal_per_100g: 165, protein_per_100g: 9, carb_per_100g: 27, fat_per_100g: 3,
    unidade_referencia: { gramas: 100, descricao: "1 concha" } },
  { id: "aveia_flocos", nome: "Aveia em flocos (seca)", categoria: "carboidrato",
    kcal_per_100g: 380, protein_per_100g: 14, carb_per_100g: 66, fat_per_100g: 7,
    unidade_referencia: { gramas: 30, descricao: "3 col sopa" } },
  { id: "pao_integral_fatia", nome: "Pao integral (fatia)", categoria: "carboidrato",
    kcal_per_100g: 260, protein_per_100g: 10, carb_per_100g: 44, fat_per_100g: 4,
    unidade_referencia: { gramas: 25, descricao: "1 fatia" } },
  { id: "pao_forma_branco", nome: "Pao de forma branco (fatia)", categoria: "carboidrato",
    kcal_per_100g: 280, protein_per_100g: 8, carb_per_100g: 52, fat_per_100g: 4,
    unidade_referencia: { gramas: 25, descricao: "1 fatia" } },
  { id: "pao_frances", nome: "Pao frances (unidade)", categoria: "carboidrato",
    kcal_per_100g: 280, protein_per_100g: 8, carb_per_100g: 54, fat_per_100g: 3,
    unidade_referencia: { gramas: 50, descricao: "1 unidade" } },
  { id: "pao_brioche", nome: "Pao de brioche (unidade)", categoria: "carboidrato",
    kcal_per_100g: 400, protein_per_100g: 12, carb_per_100g: 56, fat_per_100g: 16,
    unidade_referencia: { gramas: 50, descricao: "1 unidade" } },
  { id: "tapioca_goma", nome: "Tapioca (goma hidratada)", categoria: "carboidrato",
    kcal_per_100g: 400, protein_per_100g: 3, carb_per_100g: 93, fat_per_100g: 0,
    unidade_referencia: { gramas: 30, descricao: "3 col sopa = 1 tapioca pequena" } },
  { id: "rap10", nome: "Rap 10 / pao folha (unidade)", categoria: "carboidrato",
    kcal_per_100g: 290, protein_per_100g: 8, carb_per_100g: 49, fat_per_100g: 7,
    unidade_referencia: { gramas: 45, descricao: "1 unidade" } },

  // ===== GORDURAS =====
  { id: "azeite", nome: "Azeite extravirgem", categoria: "gordura",
    kcal_per_100g: 884, protein_per_100g: 0, carb_per_100g: 0, fat_per_100g: 100,
    unidade_referencia: { gramas: 10, descricao: "1 col sopa" } },
  { id: "pasta_amendoim", nome: "Pasta de amendoim integral", categoria: "gordura",
    kcal_per_100g: 600, protein_per_100g: 25, carb_per_100g: 20, fat_per_100g: 50,
    unidade_referencia: { gramas: 15, descricao: "1 col sopa" } },
  { id: "oleo_coco", nome: "Oleo de coco", categoria: "gordura",
    kcal_per_100g: 900, protein_per_100g: 0, carb_per_100g: 0, fat_per_100g: 100,
    unidade_referencia: { gramas: 10, descricao: "1 col sopa" } },
  { id: "manteiga", nome: "Manteiga", categoria: "gordura",
    kcal_per_100g: 720, protein_per_100g: 0.5, carb_per_100g: 0, fat_per_100g: 80,
    unidade_referencia: { gramas: 10, descricao: "1 col sopa" } },
  { id: "maionese_normal", nome: "Maionese tradicional", categoria: "gordura",
    kcal_per_100g: 700, protein_per_100g: 1, carb_per_100g: 1, fat_per_100g: 80,
    unidade_referencia: { gramas: 12, descricao: "1 col sopa" } },
  { id: "maionese_light", nome: "Maionese light", categoria: "gordura",
    kcal_per_100g: 330, protein_per_100g: 1, carb_per_100g: 10, fat_per_100g: 30,
    unidade_referencia: { gramas: 12, descricao: "1 col sopa" } },
  { id: "requeijao_light", nome: "Requeijao light", categoria: "gordura",
    kcal_per_100g: 170, protein_per_100g: 13, carb_per_100g: 7, fat_per_100g: 10,
    unidade_referencia: { gramas: 15, descricao: "1 col sopa" } },
  { id: "requeijao_cremoso", nome: "Requeijao cremoso normal", categoria: "gordura",
    kcal_per_100g: 260, protein_per_100g: 10, carb_per_100g: 4, fat_per_100g: 23,
    unidade_referencia: { gramas: 15, descricao: "1 col sopa" } },
  { id: "cream_cheese", nome: "Cream cheese", categoria: "gordura",
    kcal_per_100g: 340, protein_per_100g: 6, carb_per_100g: 4, fat_per_100g: 34,
    unidade_referencia: { gramas: 15, descricao: "1 col sopa" } },
  { id: "abacate", nome: "Abacate", categoria: "gordura",
    kcal_per_100g: 160, protein_per_100g: 2, carb_per_100g: 9, fat_per_100g: 15,
    unidade_referencia: { gramas: 100, descricao: "1/2 unidade media" } },
  { id: "castanha_para", nome: "Castanha-do-para", categoria: "gordura",
    kcal_per_100g: 660, protein_per_100g: 14, carb_per_100g: 12, fat_per_100g: 65,
    unidade_referencia: { gramas: 5, descricao: "1 unidade" } },
  { id: "amendoas", nome: "Amendoas", categoria: "gordura",
    kcal_per_100g: 580, protein_per_100g: 21, carb_per_100g: 22, fat_per_100g: 50,
    unidade_referencia: { gramas: 30, descricao: "~22 unidades" } },
  { id: "amendoim", nome: "Amendoim torrado", categoria: "gordura",
    kcal_per_100g: 570, protein_per_100g: 23, carb_per_100g: 16, fat_per_100g: 48,
    unidade_referencia: { gramas: 30, descricao: "1 punhado" } },
  { id: "castanha_caju", nome: "Castanha de caju", categoria: "gordura",
    kcal_per_100g: 550, protein_per_100g: 18, carb_per_100g: 30, fat_per_100g: 44,
    unidade_referencia: { gramas: 30, descricao: "~15 unidades" } },

  // ===== FRUTAS =====
  { id: "banana_media", nome: "Banana media", categoria: "fruta",
    kcal_per_100g: 90, protein_per_100g: 1, carb_per_100g: 23, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 unidade media" } },
  { id: "maca", nome: "Maca", categoria: "fruta",
    kcal_per_100g: 53, protein_per_100g: 0.3, carb_per_100g: 14, fat_per_100g: 0,
    unidade_referencia: { gramas: 150, descricao: "1 unidade media" } },
  { id: "laranja", nome: "Laranja", categoria: "fruta",
    kcal_per_100g: 47, protein_per_100g: 0.7, carb_per_100g: 11, fat_per_100g: 0,
    unidade_referencia: { gramas: 150, descricao: "1 unidade media" } },
  { id: "mexerica", nome: "Mexerica/Tangerina", categoria: "fruta",
    kcal_per_100g: 45, protein_per_100g: 0.7, carb_per_100g: 11, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 unidade" } },
  { id: "mamao_papaya", nome: "Mamao papaya", categoria: "fruta",
    kcal_per_100g: 43, protein_per_100g: 0.5, carb_per_100g: 11, fat_per_100g: 0,
    unidade_referencia: { gramas: 150, descricao: "1 fatia" } },
  { id: "melancia", nome: "Melancia", categoria: "fruta",
    kcal_per_100g: 30, protein_per_100g: 0.6, carb_per_100g: 8, fat_per_100g: 0,
    unidade_referencia: { gramas: 200, descricao: "1 fatia" } },
  { id: "abacaxi", nome: "Abacaxi", categoria: "fruta",
    kcal_per_100g: 50, protein_per_100g: 0.5, carb_per_100g: 13, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 fatia" } },
  { id: "morango", nome: "Morango", categoria: "fruta",
    kcal_per_100g: 32, protein_per_100g: 0.7, carb_per_100g: 8, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "6-8 unidades" } },
  { id: "manga", nome: "Manga", categoria: "fruta",
    kcal_per_100g: 60, protein_per_100g: 0.8, carb_per_100g: 15, fat_per_100g: 0,
    unidade_referencia: { gramas: 200, descricao: "1 unidade media" } },
  { id: "uva", nome: "Uva", categoria: "fruta",
    kcal_per_100g: 70, protein_per_100g: 0.7, carb_per_100g: 18, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 cacho pequeno" } },
  { id: "pera", nome: "Pera", categoria: "fruta",
    kcal_per_100g: 57, protein_per_100g: 0.4, carb_per_100g: 15, fat_per_100g: 0,
    unidade_referencia: { gramas: 150, descricao: "1 unidade media" } },
  { id: "melao", nome: "Melao", categoria: "fruta",
    kcal_per_100g: 36, protein_per_100g: 0.8, carb_per_100g: 9, fat_per_100g: 0,
    unidade_referencia: { gramas: 150, descricao: "1 fatia" } },

  // ===== VEGETAIS =====
  { id: "brocolis_cozido", nome: "Brocolis cozido", categoria: "vegetal",
    kcal_per_100g: 35, protein_per_100g: 3, carb_per_100g: 7, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 xicara" } },
  { id: "couve_refogada", nome: "Couve refogada", categoria: "vegetal",
    kcal_per_100g: 55, protein_per_100g: 3, carb_per_100g: 8, fat_per_100g: 1.5,
    unidade_referencia: { gramas: 50, descricao: "1 porcao" } },
  { id: "espinafre_cozido", nome: "Espinafre cozido", categoria: "vegetal",
    kcal_per_100g: 25, protein_per_100g: 3, carb_per_100g: 4, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 xicara" } },
  { id: "couve_flor_cozida", nome: "Couve-flor cozida", categoria: "vegetal",
    kcal_per_100g: 30, protein_per_100g: 2, carb_per_100g: 5, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 xicara" } },
  { id: "cenoura_crua", nome: "Cenoura crua", categoria: "vegetal",
    kcal_per_100g: 40, protein_per_100g: 1, carb_per_100g: 10, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 unidade media" } },
  { id: "abobrinha", nome: "Abobrinha cozida", categoria: "vegetal",
    kcal_per_100g: 20, protein_per_100g: 1, carb_per_100g: 4, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 xicara" } },
  { id: "beterraba_cozida", nome: "Beterraba cozida", categoria: "vegetal",
    kcal_per_100g: 45, protein_per_100g: 2, carb_per_100g: 10, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 xicara" } },
  { id: "tomate", nome: "Tomate", categoria: "vegetal",
    kcal_per_100g: 18, protein_per_100g: 1, carb_per_100g: 4, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1 unidade media" } },
  { id: "alface", nome: "Alface", categoria: "vegetal",
    kcal_per_100g: 15, protein_per_100g: 1, carb_per_100g: 3, fat_per_100g: 0,
    unidade_referencia: { gramas: 50, descricao: "varias folhas" } },
  { id: "rucula", nome: "Rucula", categoria: "vegetal",
    kcal_per_100g: 25, protein_per_100g: 2.5, carb_per_100g: 3.5, fat_per_100g: 0.5,
    unidade_referencia: { gramas: 30, descricao: "1 punhado" } },
  { id: "pepino", nome: "Pepino", categoria: "vegetal",
    kcal_per_100g: 15, protein_per_100g: 1, carb_per_100g: 4, fat_per_100g: 0,
    unidade_referencia: { gramas: 100, descricao: "1/2 unidade" } },
  { id: "pimentao", nome: "Pimentao (verde/vermelho)", categoria: "vegetal",
    kcal_per_100g: 20, protein_per_100g: 1, carb_per_100g: 5, fat_per_100g: 0,
    unidade_referencia: { gramas: 50, descricao: "1/2 unidade" } },

  // ===== DOCES E CORINGAS =====
  { id: "nutella", nome: "Nutella", categoria: "doce",
    kcal_per_100g: 540, protein_per_100g: 6, carb_per_100g: 57, fat_per_100g: 32,
    unidade_referencia: { gramas: 15, descricao: "1 col sopa" } },
  { id: "mel", nome: "Mel", categoria: "doce",
    kcal_per_100g: 300, protein_per_100g: 0.3, carb_per_100g: 82, fat_per_100g: 0,
    unidade_referencia: { gramas: 20, descricao: "1 col sopa" } },
  { id: "chocolate_70", nome: "Chocolate 70% cacau", categoria: "doce",
    kcal_per_100g: 540, protein_per_100g: 7, carb_per_100g: 30, fat_per_100g: 40,
    unidade_referencia: { gramas: 20, descricao: "2 quadradinhos" } },
  { id: "chocolate_leite", nome: "Chocolate ao leite", categoria: "doce",
    kcal_per_100g: 540, protein_per_100g: 7, carb_per_100g: 57, fat_per_100g: 30,
    unidade_referencia: { gramas: 30, descricao: "1 fileira" } },
  { id: "bolo_cenoura_caseiro", nome: "Bolo de cenoura caseiro", categoria: "doce",
    kcal_per_100g: 330, protein_per_100g: 5, carb_per_100g: 50, fat_per_100g: 13,
    unidade_referencia: { gramas: 60, descricao: "1 fatia media" } },
  { id: "trufa_caseira", nome: "Trufa caseira", categoria: "doce",
    kcal_per_100g: 430, protein_per_100g: 6, carb_per_100g: 47, fat_per_100g: 27,
    unidade_referencia: { gramas: 30, descricao: "1 unidade" } },
  { id: "brigadeiro", nome: "Brigadeiro", categoria: "doce",
    kcal_per_100g: 350, protein_per_100g: 4, carb_per_100g: 55, fat_per_100g: 12,
    unidade_referencia: { gramas: 20, descricao: "1 unidade" } },
  { id: "pao_queijo", nome: "Pao de queijo", categoria: "doce",
    kcal_per_100g: 330, protein_per_100g: 7, carb_per_100g: 37, fat_per_100g: 17,
    unidade_referencia: { gramas: 30, descricao: "1 unidade media" } },
  { id: "sorvete", nome: "Sorvete (cremoso/sabor)", categoria: "doce",
    kcal_per_100g: 190, protein_per_100g: 3, carb_per_100g: 25, fat_per_100g: 9,
    unidade_referencia: { gramas: 60, descricao: "1 bola" } },
  { id: "refri", nome: "Refrigerante (lata)", categoria: "bebida", unit: "ml",
    kcal_per_100g: 42, protein_per_100g: 0, carb_per_100g: 11, fat_per_100g: 0,
    unidade_referencia: { gramas: 350, descricao: "1 lata 350ml" } },

  // ===== BEBIDAS =====
  { id: "suco_laranja_natural", nome: "Suco de laranja natural", categoria: "bebida", unit: "ml",
    kcal_per_100g: 45, protein_per_100g: 0.7, carb_per_100g: 11, fat_per_100g: 0,
    unidade_referencia: { gramas: 200, descricao: "1 copo (200ml)" } },
  { id: "cafe_preto", nome: "Cafe preto (sem acucar)", categoria: "bebida", unit: "ml",
    kcal_per_100g: 2, protein_per_100g: 0, carb_per_100g: 0.5, fat_per_100g: 0,
    unidade_referencia: { gramas: 200, descricao: "1 xicara grande (200ml)" } },
  { id: "agua", nome: "Agua", categoria: "bebida", unit: "ml",
    kcal_per_100g: 0, protein_per_100g: 0, carb_per_100g: 0, fat_per_100g: 0,
    unidade_referencia: { gramas: 250, descricao: "1 copo (250ml)" } },
];

// Garantir disponibilidade global
if (typeof window !== "undefined") {
  window.TACO_FOODS = TACO_FOODS;
}
